[package]
name = "memstat"
version = "0.1.0"
edition = "2021"
description = "Naive collector of memory statistics"

[dependencies]
anyhow = "1.0.82"
human-duration = "0.1.0"
once_cell = "1.19.0"
size = "0.4.1"
